### PR TITLE
disable smart pointers (shared, unique, weak) from as_cpp<'constructible from SEXP'>

### LINKED ISSUE #96: g++ 4.8 still confused about shared_ptr<T> being constructible from SEXP
This looks like a bug of the compiler IIUC. https://github.com/apache/arrow/pull/7819/checks?check_run_id=997448752

```
array_from_vector.cpp: In function ‘std::shared_ptr<arrow::DataType> arrow::r::InferArrowTypeFromVector(SEXP) [with int VectorType = 4; SEXP = SEXPREC*]’:
3602
array_from_vector.cpp:1198:58: error: call of overloaded ‘as_cpp(SEXPREC*&)’ is ambiguous
3603
     return cpp11::as_cpp<std::shared_ptr<arrow::Array>>(x)->type();
3604
                                                          ^
3605
array_from_vector.cpp:1198:58: note: candidates are:
3606
In file included from /opt/R/4.0.2/lib/R/library/cpp11/include/cpp11.hpp:5:0,
3607
                 from ././arrow_cpp11.h:36,
3608
                 from ./arrow_types.h:22,
3609
                 from array_from_vector.cpp:20:
3610
/opt/R/4.0.2/lib/R/library/cpp11/include/cpp11/as.hpp:66:41: note: cpp11::enable_if_constructible_from_sexp<T, T> cpp11::as_cpp(SEXP) [with T = std::shared_ptr<arrow::Array>; cpp11::enable_if_constructible_from_sexp<T, T> = std::shared_ptr<arrow::Array>; SEXP = SEXPREC*]
3611
 enable_if_constructible_from_sexp<T, T> as_cpp(SEXP from) {
3612
                                         ^
3613
In file included from ./arrow_types.h:22:0,
3614
                 from array_from_vector.cpp:20:
3615
././arrow_cpp11.h:215:25: note: cpp11::enable_if_shared_ptr<T> cpp11::as_cpp(SEXP) [with T = std::shared_ptr<arrow::Array>; cpp11::enable_if_shared_ptr<T> = std::shared_ptr<arrow::Array>; SEXP = SEXPREC*]
3616
 enable_if_shared_ptr<T> as_cpp(SEXP from) {
3617
                         ^
3618
```

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #96

### CODE REVIEW

File: inst/include/cpp11/as.hpp [hunk 1]
```diff
@@ -62,7 +75,7 @@ inline bool is_convertable_without_loss_to_integer(double value) {
   return std::modf(value, &int_part) == 0.0;
 }
 
-template <typename T>
+template <typename T, typename = enable_if_t<!is_smart_ptr<T>::value>>
```
Comment (bkietz) [inline inst/include/cpp11/as.hpp:78]: I think it'd be clearer if `!is_smart_ptr` were added to the condition of `enable_if_constructible_from_sexp` with a comment explaining that it is a gcc 4.8 workaround

Comment (romainfrancois) [reply inst/include/cpp11/as.hpp:78]: I went back and forth between the two options :-)
