### PR TITLE
Move `static` local variable out of templated function

### LINKED ISSUE #298: Nested `unwind_protect()` optimization isn't working correctly
I believe that the `unwind_protect()` optimization originally added in https://github.com/r-lib/cpp11/pull/207 isn't quite right. I think it was broken after that PR was merged in https://github.com/r-lib/cpp11/commit/9a62c3a420b076d6ad48c291039421ff739dcc58 with the move to a local static object. I can prove that nested calls to `unwind_protect()` aren't being skipped as they should be.

First, here is a benchmark to show that the nested `unwind_protect()` optimization isn't working, and the performance loss is pretty brutal. The `unwind_protect()` calls happen on every iteration of the loop, because assigning an `r_string` to a `writable::strings` proxy element is wrapped in `unwind_protect()`, even though I wrapped the whole loop in `unwind_protect()` too.
https://github.com/r-lib/cpp11/blob/2aba46eb40ef6d13f1df66f1626afe82dbdf892a/inst/include/cpp11/strings.hpp#L58

```r
set.seed(123)
x <- sample(letters, 1e6, replace = TRUE)

cpp11::cpp_function("

cpp11::writable::strings test(cpp11::strings x) {
  R_xlen_t size = x.size();
  
  cpp11::writable::strings out(size);
  
  cpp11::unwind_protect([&] {
    for (R_xlen_t i = 0; i < size; ++i) {
      out[i] = x[i];
    }
  });
  
  return out;
}

")

cpp11::cpp_function("

SEXP test2(SEXP x) {
  R_xlen_t size = Rf_xlength(x);
  
  SEXP out = PROTECT(Rf_allocVector(STRSXP, size));
  
  for (R_xlen_t i = 0; i < size; ++i) {
    SET_STRING_ELT(out, i, STRING_ELT(x, i));
  }
  
  UNPROTECT(1);
  return out;
}

")

bench::mark(test(x), test2(x), iterations = 20)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 test(x)    715.35ms 751.55ms      1.31    7.63MB     1.96
#> 2 test2(x)     7.65ms   9.11ms    100.      7.63MB    35.1
```

Next, here is a video that shows how inner calls to `unwind_protect()` aren't exiting early. It uses VS Code to step through the example from above. The sequence of steps are:

- We step through the outer `unwind_protect()` call to see how it sets up the static `should_unwind_protect` local object
- Then we step through the first iteration of the `out[i] = x[i]` copy. That puts us back in `unwind_protect()`, but that static local object is _not_ yet initialized (weird right?), so we end up going back through the process of setting it up. That means `unwind_protect()` doesn't early exit here when it should.
- Then on the second iteration of `out[i] = x[i]`, the static local `should_unwind_protect` _is_ set up, but is set to `TRUE` so we again can't early exit. This continues on for the rest of the loop.

https://vimeo.com/769942052

I'm fairly certain the main problem here is that `SEXP unwind_protect(Fun&& code)` is a _template_ function, meaning that each new instantiation of it gets _its own copy of `should_unwind_protect`_, and it has to be set up every time.

I've fixed this in a branch I'll send in, and I'll explain the fix there.

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #298 

@jimhester would you mind reviewing this for me? You are the last one to have touched this code, and probably understand it better than anyone else. The #298 issue provides the backstory.

A rerun of the benchmark in #298 gives me:

```r
# Main
bench::mark(test(x), test2(x), iterations = 20)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 test(x)    715.35ms 751.55ms      1.31    7.63MB     1.96
#> 2 test2(x)     7.65ms   9.11ms    100.      7.63MB    35.1

# This PR
bench::mark(test(x), test2(x), iterations = 20)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 test(x)     69.13ms  79.75ms      11.7    7.63MB     17.5
#> 2 test2(x)     7.47ms   9.34ms      98.1    7.63MB     34.3
```

Which better matches the performance we had in 0.4.0

```r
# cpp11 0.4.0
bench::mark(test(x), test2(x), iterations = 20)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 test(x)     63.56ms   76.4ms      12.1    7.63MB     18.1
#> 2 test2(x)     7.19ms    8.3ms     103.     7.63MB     36.1
```

I also confirmed that I can't reproduce the original issue in https://github.com/r-lib/cpp11/issues/244 that forced us to move away from a global static variable.

FWIW the pattern I've used here is fairly similar to what is done in `<date>` to determine the tzdb file path
https://github.com/HowardHinnant/date/blob/22ceabf205d8d678710a43154da5a06b701c5830/src/tz.cpp#L394-L429

### CODE REVIEW

File: inst/include/cpp11/protect.hpp [hunk 1]
```diff
@@ -54,20 +54,36 @@ inline void set_option(SEXP name, SEXP value) {
...
+    // That makes this a shared global across all compilation units.
     should_unwind_protect_sexp = PROTECT(Rf_allocVector(LGLSXP, 1));
+    SET_LOGICAL_ELT(should_unwind_protect_sexp, 0, TRUE);
     detail::set_option(should_unwind_protect_sym, should_unwind_protect_sexp);
     UNPROTECT(1);
   }
 
-  Rboolean* should_unwind_protect =
-      reinterpret_cast<Rboolean*>(LOGICAL(should_unwind_protect_sexp));
-  should_unwind_protect[0] = TRUE;
```
Comment (DavisVaughan) [inline inst/include/cpp11/protect.hpp:68]: This was previously overwriting the global option to `TRUE` every time a new compilation unit needed to initialize its static local variable. I don't think we want to do that. I think we only want to initialize to `TRUE` the very first time this is created, i.e. in the if branch above.

File: inst/include/cpp11/protect.hpp [hunk 2]
```diff
@@ -54,20 +54,36 @@ inline void set_option(SEXP name, SEXP value) {
...
+  return reinterpret_cast<Rboolean*>(LOGICAL(should_unwind_protect_sexp));
+}
+
+inline Rboolean* access_should_unwind_protect() {
+  // Setup is run once per compilation unit, but all compilation units
+  // share the same global option, so each compilation unit's static pointer
+  // will point to the same object.
+  static Rboolean* p_should_unwind_protect = setup_should_unwind_protect();
```
Comment (DavisVaughan) [inline inst/include/cpp11/protect.hpp:77]: The function holding the static local variable is no longer templated, so each compilation unit will only have to run `setup_should_unwind_protect()` 1 time

File: inst/include/cpp11/protect.hpp [hunk 3]
```diff
@@ -54,20 +54,34 @@ inline void set_option(SEXP name, SEXP value) {
   SETCAR(opt, value);
 }
 
-inline Rboolean& get_should_unwind_protect() {
+inline Rboolean* setup_should_unwind_protect() {
```
Comment (DavisVaughan) [inline inst/include/cpp11/protect.hpp:57]: I can continue to make this return a reference rather than a pointer, if anyone has any preference. It seemed a little easier for me to understand if this was a pointer.

**Comment by romainfrancois** [comment]
LGTM. Not strictly related to this PR's business, but should we be concerned about the option being set to something that is not a logical ?

File: inst/include/cpp11/protect.hpp (hunk 3 above)
Comment (romainfrancois) [reply inst/include/cpp11/protect.hpp:57]: I don't mind it being a pointer.

**Comment by romainfrancois** [comment]
I can confirm the performance gain: 

`main`: 

```
> bench::mark(test(x), test2(x), iterations = 20)
# A tibble: 2 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result            memory               time            gc               
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>            <list>               <list>          <list>           
1 test(x)    232.65ms 236.53ms      4.09    7.63MB     7.77    20    38      4.89s <chr [1,000,000]> <Rprofmem [149 × 3]> <bench_tm [20]> <tibble [20 × 3]>
2 test2(x)     4.39ms   4.53ms    191.      7.63MB    38.2     20     4   104.82ms <chr [1,000,000]> <Rprofmem [1 × 3]>   <bench_tm [20]> <tibble [20 × 3]>
```

`#299` : 

```
> bench::mark(test(x), test2(x), iterations = 20)
# A tibble: 2 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result            memory               time            gc               
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>            <list>               <list>          <list>           
1 test(x)     32.17ms  34.15ms      25.9    7.63MB     38.9    20    30      772ms <chr [1,000,000]> <Rprofmem [225 × 3]> <bench_tm [20]> <tibble [20 × 3]>
2 test2(x)     4.43ms   4.54ms     144.     7.63MB     36.0    20     5      139ms <chr [1,000,000]> <Rprofmem [1 × 3]>   <bench_tm [20]> <tibble [20 × 3]>
```

**Comment by DavisVaughan** [comment]
@romainfrancois we should also try looking at this comment from Jim, possibly as a (nicer?) alternative to this PR https://github.com/r-lib/cpp11/commit/9a62c3a420b076d6ad48c291039421ff739dcc58#r90124412
